AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for a challenge lab environment with VPC, EC2, and S3"

Parameters:
  VpcCidr:
    Type: String
    Description: "CIDR block for the VPC"
    Default: 10.0.0.0/24

  PrivateSubnetCidr:
    Type: String
    Description: "CIDR block for the private subnet"
    Default: 10.0.0.0/28

  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "Amazon Linux 2 AMI from SSM Parameter Store"
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

  # VPC
  VPCforCloudFormation:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPCforCloudFormation

  # Internet Gateway
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW-CloudFormation

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPCforCloudFormation

  # Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCforCloudFormation
      CidrBlock: !Ref PrivateSubnetCidr
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        !Select
          - 0
          - !GetAZs
            - !Ref AWS::Region
      Tags:
        - Key: Name
          Value: Private Subnet

  # Security Group
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH Access
      VpcId: !Ref VPCforCloudFormation
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SSH Security Group

  # EC2 Instance
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmazonLinuxAMIID
      InstanceType: t3.micro
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: Private EC2 Instance

  # S3 Bucket
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: MySecureS3Bucket

Outputs:
  VpcId:
    Description: "VPC ID"
    Value: !Ref VPCforCloudFormation

  SubnetId:
    Description: "Private Subnet ID"
    Value: !Ref PrivateSubnet

  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref AppInstance

  S3BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref MyS3Bucket
